### ISSUE TITLE
Add upper bound to `errors` dependency

### ISSUE THREAD

**Issue by Gabriella439** [danidiaz/pianola#2]
`errors-2.0` will switch to use `ExceptT` instead of `EitherT`.  If that will break your package then add an upper bound of `errors < 2.0` to your dependencies.

**Comment by danidiaz** [comment]
Closing because the pianola package is currently deprecated. If I revive it at some point, I'll use the new version of errors. Tanks for the notification.

**Comment by Gabriella439** [comment]
You're welcome!
